### ISSUE TITLE
Charge doesn't work when on an enemy.

### ISSUE THREAD

**Issue by KrashBoomBang** [FireEmblemUniverse/SkillSystem_FE8#124]
So I'm making a hack and there's a boss with a weapon that has the skill Charge on it. Problem is, the skill only works if a player unit has it, not an enemy unit. Here's a link to the builder error report I made. https://drive.google.com/open?id=1RNuI3fkQLAWMkfcSrN8R7i6sdSM-DZkT

**Comment by KrashBoomBang** [comment]
Here's a link to the builder error report I made about it. https://drive.google.com/open?id=1RNuI3fkQLAWMkfcSrN8R7i6sdSM-DZkT

**Comment by sme23** [comment]
Charge is based on # of tiles moved, which is only tracked by the game because of Canto and only tracked on player units because only player units can Canto. Therefore, changing this behavior would require a significant rewrite of systems to have the game track how far non-player units move which likely would only occur alongside the implementation of enemy canto AI.
