### ISSUE TITLE
Freeze/Crash bug from viewing Unit pages

### ISSUE THREAD

**Issue by mill5488** [FireEmblemUniverse/SkillSystem_FE8#295]
![c1](https://user-images.githubusercontent.com/30009086/129465804-2bd15bc1-3a78-4f17-9c84-7c504ad31dab.PNG)
Doing a clean install of the most recent commit causes freezing/crashing issues when attempting to view Unit (Stat) pages. (Regardless of any settings of the EngineHacks/Config.event file, and present on all 3 of the following emulators: VBA, mGBA, and No$gba Debugger)

Doing a clean install with a previous commit [ af4b55d8c5a6ae0f99c45aeb1e70d8a994675b91 ] - june 21 seems to have fixed the issue.

**Comment by sme23** [comment]
Is there anything more to triggering this than just pressing R on a unit on the map? This is working fine for me in any version e1028d3b4ed26ad0c069c388a48c790d1ab9fe55 (which I assume you had? it was the current state of the repository for the past few weeks) or newer

**Comment by mill5488** [comment]
(Finally back to civilization) 

It was indeed the current (at the time) state of the repository. The only specific other thing that I noticed was that it typically didn't occur within the first couple of turns in the Prologue or Chapter 1. Usually after a couple of turns, (not sure if this was dictated by a few combats occurring or not) it could start happening pretty consistently. I also noticed that there was a weird display in the lower left corner of the current map screen. Where it shows the status of the character your cursor is on, currently. (Name, portrait, HP). I noticed that the HP text would replace with seemingly unrelated data Like, "Berserk turn phase" would slowly spell out in a scrolling fashion, and other odd things. 

I will re-test later with a clean install, to see if it still happens for me so I can be more helpful.

**Comment by sme23** [comment]
Thanks for the follow-up, had the information I needed to find & fix this

What was happening was when using an item or staff the target was having a status effect of ID `0xF` applied to them, which is out of range causing a glitchy minimug box label and the status screen crashing when trying to get the name of the status to display. I had incidentally already made a fix for this issue in another environment because a similar thing was happening there, porting that over here fixes things and it shouldn't happen anymore as of 2a2a54094b0ce02e650aa0843a75618e1342076a.

I'm also going to mention @Teraspark, as this is staff & status-related and recent so there may be some underlying issue with a recent Item Effect Revamp change relating to validating the status to apply after battle (something that wouldn't treat `0xFF` as no status, the implemented fix is just changing when it is `0xFF` to mean no status to instead be `0`) that caused this in the first place, since I don't think anything else changed recently touches that kind of stuff
