### ISSUE TITLE
Looking at items while riding a ballista is bugged

### ISSUE THREAD

**Issue by LeonarthCG** [FireEmblemUniverse/SkillSystem_FE8#31]
The info for items and the affinity icon is wrong when looking at items while mounted in a ballista.

To reproduce: look at the unit's items, get in a ballista, look at them again

**Comment by StanHash** [comment]
This is vanilla behavior. The stats and icons displayed are those with the ballista "equipped". Since there is no check for weapon type for ballista items, It is easier to get the icon to be wrong (by having the weapon type of the ballista be item (9) or something).

This could warrant a fix at some point, but this isn't a skill system issue.
