### ISSUE TITLE
EMS

### ISSUE THREAD

**Issue by We-Who-Belong** [FireEmblemUniverse/SkillSystem_FE8#426]
(I intend to work on this. But I need to scope the problem!)

In [SrcModules/SaveUnitExpanded](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/EngineHacks/Necessary/ExpandedModularSave/SrcModules/SaveUnitExpanded.s#L11), Magic is called out as existing.

This contradicts with [SrcModules/SaveUnitExpandedStrmag](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/EngineHacks/Necessary/ExpandedModularSave/SrcModules/SaveUnitExpandedStrmag.s) since that implies you, well, *wouldn't have* mag unless you're using the strmag version.

But the data saves and loads assuming that that space *is* there. The only differences in them are lines ~126 and ~290:

[In the PackGameSaveUnit section](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/EngineHacks/Necessary/ExpandedModularSave/SrcModules/SaveUnitExpandedStrmag.s#L125-L128)
```	mov r3, #0x3A
	ldrb r2, [r1, r3] @ r2 = Unit->mag
	strb r2, [r0, #0x04] @ GameSaveUnit->mag = Unit->mag
```

[Compared to ](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/EngineHacks/Necessary/ExpandedModularSave/SrcModules/SaveUnitExpanded.s#L126-L129)
```
	mov  r2, #0          @ r2 = Unit->mag
	strb r2, [r0, #0x04] @ GameSaveUnit->mag = Unit->mag
```

[And their sisters, loading:](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/EngineHacks/Necessary/ExpandedModularSave/SrcModules/SaveUnitExpandedStrmag.s#L289-L291)
```
	ldrb r2, [r5, #0x04] @ r2 = GameSaveUnit->mag
	mov r3, #0x3A
	strb r2, [r4, r3]
```

[Marking the second diff:](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/EngineHacks/Necessary/ExpandedModularSave/SrcModules/SaveUnitExpanded.s#L288-L289)
```	ldrb r2, [r5, #0x04] @ r2 = GameSaveUnit->mag
	@ do nothing         @ Unit->mag = GameSaveUnit->mag
```
Because of this, the save data for non-Strmag is going to include an empty slot for Magic --

MaxHP Strength Zero Skill Speed Defense ...

Which is not significant, but adds up across the **130** units saved in suspend. It wastes enough space for two whole units.

The same issue is present in the Stairs version, as well. 

Also why is the base size padded? For what purpose?

---

The next part of this is where this becomes somewhat important:

According to these files, a Player Unit is 0x34 bytes, and there can be 62 of them, and a nonplayer unit is 0x38 bytes and there are 50 red and 20 green ones. 
These unit sizes are constant for all four versions of this and these unit counts are defined in the [memory allocation plans](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/EngineHacks/Necessary/ExpandedModularSave/ExModularSave.event#L185-L192)

However, these values are not agreed upon by other pieces of code and the difference isn't clear:

[SrcCore/MsuFuncs.c](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/EngineHacks/Necessary/ExpandedModularSave/SrcCore/MSuFuncs.c#L17-L41)
```void MSu_SavePlayerUnits(void* target, unsigned size) {
	for (unsigned i = 0; i < 51; ++i) {
[...]
	// Save reds
	for (unsigned i = 0; i < 50; ++i) {
[...]
	// Save greens
	for (unsigned i = 0; i < 10; ++i) {
```

And much more damningly, [SrcCore/MSuFuncs.c](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/EngineHacks/Necessary/ExpandedModularSave/SrcCore/MSuFuncs.c#L43-L51)
```void MSu_LoadOtherUnits(void* source, unsigned size) {
	// Load reds
	for (unsigned i = 0; i < 50; ++i)
		UnpackUnitStructFromSuspend(source + 0x34*i, GetUnit(0x81+i));

	// Load greens
	for (unsigned i = 0; i < 10; ++i)
		UnpackUnitStructFromSuspend(source + 0x34*(50+i), GetUnit(0x41+i));
}
```
... But we just got done saying that those're $38 bytes. And the plan says as much.
And yet, that sure is a hardcoded $34 that we're looking at that doesn't match any of this data.

There's incorrect comments like:
[PackOtherSuspendSaveUnit](https://github.com/FireEmblemUniverse/SkillSystem_FE8/blob/master/EngineHacks/Necessary/ExpandedModularSave/SrcModules/SaveUnitExpanded.s#L535)
```	@ arguments:
	@ - r0 = target buffer address
	@ - r1 = source unit
	@ returns:
	@ - r0 = target buffer address
[...]
	mov  r2, #0x2C
	add  r2, r0 @ r2 = su+0x2C, for easier addressing (0x2C+ is out of ldrb/strb range)
```
But r0 is the target buffer not source nor save. The later comments use "su" as save/suspend unit
This r2 index is used for both as an initial increment forward from both r0 and r1 because it's done after "PackGameSaveUnit", which is responsible for the rest of those bytes.

This overall isn't actually an issue because the assembly makes the comment clear but sure makes it harder to understand something that's already really complicated.

This issue is getting so long my browser is having trouble showing it to me so I'm going to submit this though it's incomplete.

**Comment by StanHash** [comment]
Yo! I don't really know if there is a problem or if we are just discussing the hack's design but since I made most of this maybe I can say useful things.

Most of the decisions I made making EMS and (especially) the Skill System's Save Unit Expansion are not necessarily correct (or at the very least the most correct) and the entire implementation is very much improvable.

---

The unused magic byte exists because I wanted to be fancy and account for the (then) future implementation of a strength/magic split. At the time, we had plenty of space left in the suspend layout so the extra allocated byte per unit was no big deal.

Because of how this is implemented, there's no reason for the save/suspend unit layout sizes to be aligned to 4, I believe (there is in vanilla, however).

I don't like how there's 2² different implementations of the same module. This is one of the most visible symptoms of the more general "the Skill System tries to please everyone to the detriment of its own coherence" issue that I have.

---

The `MSu_(Save|Load)(Player|Other)Units` (and `MSa_(Save|Load)Units`) functions are **unused** in the skill system. They are leftovers from base EMS which only implements the vanilla save layout (the hardwired sizes and amounts are thus vanilla, not the expanded ones). The skill system uses the ESU variants exclusively.

---

> [...]
> But r0 is the target buffer not source nor save. The later comments use "su" as save/suspend unit

here target buffer = save unit.
