### ISSUE TITLE
Skill Extensions not getting the icons

### ISSUE THREAD

**Issue by cadebitterleaf** [FireEmblemUniverse/SkillSystem_FE8#675]
![Screenshot (124)](https://github.com/FireEmblemUniverse/SkillSystem_FE8/assets/41345492/390b02bb-ade1-4ad8-b3b3-4f55ccb493c5)
![Screenshot (123)](https://github.com/FireEmblemUniverse/SkillSystem_FE8/assets/41345492/a01a40d4-ff47-456a-9f64-1c99b08ec2aa)
I keep getting an error when I try to open skill config in FeBuilder.  I just installed the system.  Did I install it incorrectly?

**Comment by Veslyquix** [comment]
Febuilder supports specific older builds of a slightly modified version of this buildfile. The latest patch says July 2022. Install skillsys via febuilder's Patches menu if you wish to edit the rom with febuilder. 

I think feb expects skillsys data to be in a specific block of ROM, so things may only display if you have free space defined to build there. See the first lines of CustomDefinitions.event - using `#define FreeSpace 0xb2a610` instead of 0xFE4000 might make feb display it.

**Comment by cadebitterleaf** [comment]
Unfortunately uncommenting #define FreeSpace 0xb2a610 did not work.  However, thank you for the help.  I'll just add it through the febuilder patch system.

**Comment by ZeikoLeMonde** [comment]
Adding to this, apparently using `#define FreeSpace 0xb2a610` as Vesly suggested worked before #616.

**Comment by Veslyquix** [comment]
Febuilder searches for a sequence of bytes to find data. All it takes is a small change here to have febuilder unable to find something - it was not intended to be used to edit icons for skillsys master. 

If you want febuilder support, install the 2022 patch, or edit how febuilder finds the table. Here's an example of how it finds NaturalCover for that patch: 
https://github.com/FEBuilderGBA/FEBuilderGBA/blob/af4234570e960d39747294c538e3cedbd751dee5/FEBuilderGBA/bin/Debug/config/patch2/FE8U/skill20220703/PATCH_NaturalCoverDamage.txt#L4
